### ISSUE TITLE
"Uncaught Error: Class not found" when running with --xml flag

### ISSUE THREAD

**Issue by mwurster01** [sebastianbergmann/phpcov#76]
While phpcov works great with the -- clover and the --html flag, I'm experiencing the following error when running phpcov with the --xml flag:

```
Generating code coverage report in PHP format ...PHP Fatal error:  Uncaught Error: Class 'TheSeer\Tokenizer\Tokenizer' not found in phar:///opt/phpcov/phpcov.phar/phpunit/php-code-coverage/src/Report/Xml/Source.php:37
Stack trace:
#0 phar:///opt/phpcov/phpcov.phar/phpunit/php-code-coverage/src/Report/Xml/Facade.php(165): SebastianBergmann\CodeCoverage\Report\Xml\Source->setSourceCode('<?php\n\nnamespac...')
#1 phar:///opt/phpcov/phpcov.phar/phpunit/php-code-coverage/src/Report/Xml/Facade.php(121): SebastianBergmann\CodeCoverage\Report\Xml\Facade->processFile(Object(SebastianBergmann\CodeCoverage\Node\File), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
#2 phar:///opt/phpcov/phpcov.phar/phpunit/php-code-coverage/src/Report/Xml/Facade.php(117): SebastianBergmann\CodeCoverage\Report\Xml\Facade->processDirectory(Object(SebastianBergmann\CodeCoverage\Node\Directory), Object(SebastianBergmann\CodeCoverage\Report\Xml\Directory))
#3 phar:///opt/phpcov/phpcov.phar/phpunit/php-code-coverage/src/Report/Xml/Facade.php(117): SebastianBergmann\CodeCoverage\Report\Xml\Facade in phar:///opt/phpcov/phpcov.phar/phpunit/php-code-coverage/src/Report/Xml/Source.php on line 37
```

**Comment by jakesyl** [comment]
Hi, how did you fix this?
